// Add Post
export const POST_ADD_POST_INPROGRESS = 'POST_ADD_POST_INPROGRESS'
export const POST_ADD_POST_SUCCESS = 'POST_ADD_POST_SUCCESS'
export const POST_ADD_POST_FALIUER = 'POST_ADD_POST_FALIUER'

// Load Post
export const FETCH_POSTS_INPROGRESS = 'FETCH_POSTS_INPROGRESS'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FALIUER = 'FETCH_POSTS_FALIUER'